### ISSUE TITLE
I got problems on some compilations

### ISSUE THREAD

**Issue by cryptid11** [xorpd/asm_prog_ex_yasm#2]
I link training.s from the folder - how can we add env variable INCLUDE on linux? (assuming it works like on windows) - and this is the result I got:
  
`file=0_strange_calc; yasm -felf $file.asm; gcc $file.o -o $file -m32` works perfectly
```
$ file=4_bad_cmp; yasm -felf $file.asm; gcc $file.o -o $file -m32
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib32/Scrt1.o: In function `_start':
(.text+0x28): undefined reference to `main'
collect2: error: ld returned 1 exit status
``` 
doesnt works

why is that? 0_strange_calc.asm seems really similar to 4_bad_cmp.asm!

**Comment by blankwall** [comment]
There is a small error in the code you need to add this

```
section .text

    ; The program begins here:

main:                             <------- add this main declaration
    call    read_hex
    mov     ecx,eax
    call    read_hex
    sub     eax,ecx
    js      b1
```

**Comment by blankwall** [comment]
Updated

**Comment by cryptid11** [comment]
what an idiot! thanks :D

**Comment by blankwall** [comment]
Happens to all of us from time to time! happy hacking!

**Comment by xorpd** [comment]
@blankwall : Thanks!
